/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HowToOrderRouteImport } from './routes/how-to-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaptopsIndexRouteImport } from './routes/laptops/index'
import { Route as LaptopsLenovoRouteImport } from './routes/laptops/lenovo'
import { Route as LaptopsHpRouteImport } from './routes/laptops/hp'
import { Route as LaptopsDellRouteImport } from './routes/laptops/dell'
import { Route as LaptopsSlugRouteImport } from './routes/laptops/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToOrderRoute = HowToOrderRouteImport.update({
  id: '/how-to-order',
  path: '/how-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsIndexRoute = LaptopsIndexRouteImport.update({
  id: '/laptops/',
  path: '/laptops/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsLenovoRoute = LaptopsLenovoRouteImport.update({
  id: '/laptops/lenovo',
  path: '/laptops/lenovo',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsHpRoute = LaptopsHpRouteImport.update({
  id: '/laptops/hp',
  path: '/laptops/hp',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsDellRoute = LaptopsDellRouteImport.update({
  id: '/laptops/dell',
  path: '/laptops/dell',
  getParentRoute: () => rootRouteImport,
} as any)
const LaptopsSlugRoute = LaptopsSlugRouteImport.update({
  id: '/laptops/$slug',
  path: '/laptops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-to-order': typeof HowToOrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/laptops/$slug': typeof LaptopsSlugRoute
  '/laptops/dell': typeof LaptopsDellRoute
  '/laptops/hp': typeof LaptopsHpRoute
  '/laptops/lenovo': typeof LaptopsLenovoRoute
  '/laptops/': typeof LaptopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-to-order': typeof HowToOrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/laptops/$slug': typeof LaptopsSlugRoute
  '/laptops/dell': typeof LaptopsDellRoute
  '/laptops/hp': typeof LaptopsHpRoute
  '/laptops/lenovo': typeof LaptopsLenovoRoute
  '/laptops': typeof LaptopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-to-order': typeof HowToOrderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/laptops/$slug': typeof LaptopsSlugRoute
  '/laptops/dell': typeof LaptopsDellRoute
  '/laptops/hp': typeof LaptopsHpRoute
  '/laptops/lenovo': typeof LaptopsLenovoRoute
  '/laptops/': typeof LaptopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-to-order'
    | '/sitemap.xml'
    | '/laptops/$slug'
    | '/laptops/dell'
    | '/laptops/hp'
    | '/laptops/lenovo'
    | '/laptops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-to-order'
    | '/sitemap.xml'
    | '/laptops/$slug'
    | '/laptops/dell'
    | '/laptops/hp'
    | '/laptops/lenovo'
    | '/laptops'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-to-order'
    | '/sitemap.xml'
    | '/laptops/$slug'
    | '/laptops/dell'
    | '/laptops/hp'
    | '/laptops/lenovo'
    | '/laptops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowToOrderRoute: typeof HowToOrderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LaptopsSlugRoute: typeof LaptopsSlugRoute
  LaptopsDellRoute: typeof LaptopsDellRoute
  LaptopsHpRoute: typeof LaptopsHpRoute
  LaptopsLenovoRoute: typeof LaptopsLenovoRoute
  LaptopsIndexRoute: typeof LaptopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-order': {
      id: '/how-to-order'
      path: '/how-to-order'
      fullPath: '/how-to-order'
      preLoaderRoute: typeof HowToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/': {
      id: '/laptops/'
      path: '/laptops'
      fullPath: '/laptops/'
      preLoaderRoute: typeof LaptopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/lenovo': {
      id: '/laptops/lenovo'
      path: '/laptops/lenovo'
      fullPath: '/laptops/lenovo'
      preLoaderRoute: typeof LaptopsLenovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/hp': {
      id: '/laptops/hp'
      path: '/laptops/hp'
      fullPath: '/laptops/hp'
      preLoaderRoute: typeof LaptopsHpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/dell': {
      id: '/laptops/dell'
      path: '/laptops/dell'
      fullPath: '/laptops/dell'
      preLoaderRoute: typeof LaptopsDellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laptops/$slug': {
      id: '/laptops/$slug'
      path: '/laptops/$slug'
      fullPath: '/laptops/$slug'
      preLoaderRoute: typeof LaptopsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowToOrderRoute: HowToOrderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LaptopsSlugRoute: LaptopsSlugRoute,
  LaptopsDellRoute: LaptopsDellRoute,
  LaptopsHpRoute: LaptopsHpRoute,
  LaptopsLenovoRoute: LaptopsLenovoRoute,
  LaptopsIndexRoute: LaptopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
